sudo: false
language: go
go:
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x

install:
  - go get -v -d -t github.com/golang/protobuf/...
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d $HOME/protoc

env:
  - PATH=$HOME/protoc/bin:$PATH

script:
  - make all test
